In [8]:
#import dependencies
import pandas as pd
import numpy as np
import csv
%matplotlib notebook

In [10]:
#read csv and turn into df
file = "mortality_data.csv"

# Read our Kickstarter data into pandas
mortality_data_df = pd.read_csv(file)
mortality_data_df.head(1)

,Location,FIPS,Category,"Mortality Rate, 1980*","Mortality Rate, 1980* (Min)","Mortality Rate, 1980* (Max)","Mortality Rate, 1985*","Mortality Rate, 1985* (Min)","Mortality Rate, 1985* (Max)","Mortality Rate, 1990*",...,"Mortality Rate, 2005* (Max)","Mortality Rate, 2010*","Mortality Rate, 2010* (Min)","Mortality Rate, 2010* (Max)","Mortality Rate, 2014*","Mortality Rate, 2014* (Min)","Mortality Rate, 2014* (Max)","% Change in Mortality Rate, 1980-2014","% Change in Mortality Rate, 1980-2014 (Min)","% Change in Mortality Rate, 1980-2014 (Max)"
0,United States,NaN,Neonatal disorders,9.18,8.83,9.93,6.91,6.73,7.36,6.09,...,4.55,3.75,3.43,3.85,3.32,3.02,3.45,-63.85,-68.95,-61.55

In [12]:
mortality_data_df.describe()

,FIPS,"Mortality Rate, 1980*","Mortality Rate, 1980* (Min)","Mortality Rate, 1980* (Max)","Mortality Rate, 1985*","Mortality Rate, 1985* (Min)","Mortality Rate, 1985* (Max)","Mortality Rate, 1990*","Mortality Rate, 1990* (Min)","Mortality Rate, 1990* (Max)",...,"Mortality Rate, 2005* (Max)","Mortality Rate, 2010*","Mortality Rate, 2010* (Min)","Mortality Rate, 2010* (Max)","Mortality Rate, 2014*","Mortality Rate, 2014* (Min)","Mortality Rate, 2014* (Max)","% Change in Mortality Rate, 1980-2014","% Change in Mortality Rate, 1980-2014 (Min)","% Change in Mortality Rate, 1980-2014 (Max)"
count,67053.000000,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000,...,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000,67074.000000
mean,29898.810836,51.671032,47.379253,56.308657,49.866569,45.969582,54.057134,47.743719,44.097959,51.636138,...,48.097184,41.337479,37.801818,45.137414,41.637265,37.880742,45.684322,14.043938,-13.944556,57.137249
std,15512.679073,112.480259,105.565019,119.717786,105.974691,99.885155,112.315265,96.296913,90.909058,101.863539,...,83.917135,71.880854,67.246226,76.708869,72.285456,67.331225,77.500770,107.484136,76.312639,159.884896
min,1.000000,0.020000,0.010000,0.030000,0.010000,0.010000,0.020000,0.010000,0.010000,0.020000,...,0.030000,0.020000,0.010000,0.030000,0.010000,0.000000,0.030000,-99.120000,-99.920000,-95.690000
25%,18101.000000,1.800000,1.350000,2.440000,1.980000,1.500000,2.620000,2.680000,2.050000,3.490000,...,3.820000,1.690000,1.240000,2.410000,1.640000,1.190000,2.240000,-31.420000,-47.090000,-11.780000
50%,29125.000000,14.600000,12.070000,17.380000,14.150000,11.840000,16.695000,13.860000,11.770000,16.130000,...,16.420000,14.370000,12.280000,16.460000,14.440000,12.230000,16.670000,-8.520000,-27.670000,17.620000
75%,45055.000000,38.390000,34.727500,42.277500,38.640000,35.187500,42.280000,39.810000,36.437500,43.370000,...,45.490000,38.707500,34.650000,42.950000,39.177500,34.720000,43.790000,27.087500,-3.452500,73.870000
max,56045.000000,967.180000,859.120000,1084.320000,903.070000,802.210000,1000.420000,789.520000,705.880000,874.120000,...,667.820000,539.930000,486.490000,610.380000,545.230000,509.270000,585.130000,2205.830000,1617.220000,5403.230000